### PR TITLE
Jsonschema pr2

### PR DESCRIPTION
**Pull request by sunitakawane**
This PR includes
- cljs test config
- src and test files converted to cljc/cljs

ToDo
change official-test-cljs to run cljs tests
add tests for regex-cljc

### CODE REVIEW

**Comment by malcolmsparks** [comment]
Thank you. This is looking in good shape. How do I run the tests?

**Comment by sunitakawane** [comment]
To run tests use 
`make test`

I just tried that but some files are not up to date. Let me fix and resend the pr . Sorry about that.

**Comment by malcolmsparks** [comment]
Thanks.

**Comment by malcolmsparks** [comment]
One question. Do we need the node-based files i/o in the actual library or just in the tests? If so, put the dep in a test alias in deps.edn. Let me know if you're not clear what I'm asking.

**Comment by sunitakawane** [comment]
we need it only for tests , I can add -t(target) node (target node) in the deps.edn. I will try that.

**Comment by sunitakawane** [comment]
pushed changes to the same `jsonschema-pr2 ` branch, please get the latest and to run the tests use
`make test`

**Comment by malcolmsparks** [comment]
This is a good start. 

We need this to get to a point where there is one validate.cljc, one schema.cljc, and ideally one regex (although I see formats as one area where they'll be some digression).

Also, have you been able to get the official test suite running? I think this is necessary to do via a browser. Perhaps you can try to slurp in there json tests from https://github.com/json-schema-org/JSON-Schema-Test-Suite.

**Pull request closed without merging**
